// Generated by ts-to-zod
import { z } from "zod";

export const d3CardLayoutConfigSchema = z.object({
  margin: z
    .object({
      top: z.number().optional(),
      right: z.number().optional(),
      bottom: z.number().optional(),
      left: z.number().optional(),
    })
    .optional(),
});

export const d3CardSeriesConfigGroupBySchema = z.object({
  func: z.union([
    z.literal("raw"),
    z.literal("avg"),
    z.literal("max"),
    z.literal("min"),
    z.literal("first"),
    z.literal("last"),
    z.literal("sum"),
    z.literal("median"),
    z.literal("delta"),
    z.literal("diff"),
  ]),
  duration: z.string(),
  fill: z
    .union([z.literal("null"), z.literal("last"), z.literal("zero")])
    .optional(),
});

export const d3CardSeriesConfigStatisticsSchema = z.object({
  type: z.union([
    z.literal("mean"),
    z.literal("min"),
    z.literal("max"),
    z.literal("sum"),
    z.literal("state"),
  ]),
  period: z.union([
    z.literal("5minute"),
    z.literal("hour"),
    z.literal("day"),
    z.literal("week"),
    z.literal("month"),
  ]),
  align: z
    .union([z.literal("start"), z.literal("middle"), z.literal("end")])
    .optional(),
});

export const d3CardSeriesConfigSchema = z.object({
  entity: z.string(),
  meta: z.record(z.any()).optional(),
  fetch_history: z
    .object({
      span: z.string(),
    })
    .optional(),
  transform: z.string().optional(),
  attribute: z.string().optional(),
  cache_history: z.boolean().optional(),
  group_by: d3CardSeriesConfigGroupBySchema.optional(),
  statistics: d3CardSeriesConfigStatisticsSchema.optional(),
});

export const d3CardConfigSchema = z.object({
  title: z.string(),
  height: z.string(),
  series: z.array(d3CardSeriesConfigSchema),
  d3_code: z.string(),
  use_compression: z.boolean().optional(),
  layout: d3CardLayoutConfigSchema.optional(),
});
